### ISSUE TITLE
[feature] Hofsäss and Stegmaier propose a BCA without surface binding energy

### ISSUE THREAD

**Issue by drobnyjt** [lcpp-org/RustBCA#185]
**Is your feature request related to a problem? Please describe.**
Surface binding energies are problematic in the BCA because they are 1) difficult to measure 2) have to sometimes be adjusted seemingly arbitrarily

**Proposed solution**
Paper is here:
https://doi.org/10.1016/j.nimb.2022.02.012

**Additional context**
If this works, it would be a huge deal for BCA models. Removing the semi-arbitrary planar model of the surface binding energy would remove a very significant free parameter from the model

**Comment by drobnyjt** [comment]
Having read the paper more carefully, some thoughts.

1) They don't quite demonstrate that the BBE model is superior than the SBE model. In fact, for their silicon sputtered angular distributions, it is significantly worse.

2) The model requires feedback between distributions (local nuclear energy loss) and the local bulk binding energies. I'm not sure how this works in their code; you would have to iterate back and forth to reach some sort of equilibrium? It sounds like their code runs normally in a dynamic code, with an implied fluence, which is not the goal of RustBCA.

3) I wonder - if this were combined with attractive-repulsive potentials, would that get better results?

**Comment by JASory** [comment]
Can you [email it](mailto:jasory@rust-cas.org) to me?

**Comment by drobnyjt** [comment]
> Can you [email it](mailto:jasory@rust-cas.org) to me?

Not without breaking copyright law! Your best bet for access might be to email the authors.

**Comment by drobnyjt** [comment]
In the end, I don't think this is worth pursuing unless a second paper improving upon the first comes out.
