### ISSUE TITLE
[question] HDF5 File or Uniform Distribution

### ISSUE THREAD

**Issue by mashbur4** [lcpp-org/RustBCA#201]
I am attempting to place incident particles at multiple different positions on a tungsten sphere target (essentially a simplified version of flux). Rather than typing out the particle positions and directions for each of the positions by hand, I was hoping that either an HDF5 file or the Uniform distribution could be used as a much easier implementation than just hardcoding each position. However, I am unsure of the HDF5 file structure and how the program handles these files. I have also not been able to get the uniform distribution to work either. Are there any examples available of either of these methods being used or does anybody have any experience using them? Thank you for any assistance.

**Comment by drobnyjt** [comment]
The HDF5 input file is pretty underdeveloped, since nobody ever needed to use it - maybe your question is an indication that it should receive some attention! I don't have any examples on hand, I think, and would have to delve into the source code to make one as it stands.

However, I would recommend using the distribution input for this use case. I recently resolved an issue concerning the documentation for the uniform distributions being wrong; can you share the input file you tried and what error messages you got, if any?

**Comment by mashbur4** [comment]
So I have run this file for only 100 particles and the error message I receive is:

"    Finished release [optimized] target(s) in 24.69s
     Running `target/release/RustBCA SPHERE tungsten_sphere_150_100A.toml`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Could not parse TOML file. Be sure you are using the correct input file mode (e.g., ./RustBCA SPHERE sphere.toml or RustBCA.exe 0D mesh_0d.toml).

Caused by:
    expected a right bracket, found a left brace at line 42 column 23', src/sphere.rs:14:189
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace"

I have attempted to go back and fix this multiple time but each time I change something, it continues to tell me some variation of a bracket expected where something else was found. Attached is the input script. (Had to change to txt file)
[tungsten_sphere_150_100A.txt](https://github.com/lcpp-org/RustBCA/files/10035381/tungsten_sphere_150_100A.txt)

**Comment by drobnyjt** [comment]
Okay, I reproduced the error and have solved the problem; it looks like I didn't actually fix the documentation, haha - not sure exactly what happened, but the documentation for the distributions is still completely wrong; I'll fix that now.

Replace line 42 with:
```
pos = [[-105,{min=-100, max=100},0]]
```

And it should work.

**Comment by drobnyjt** [comment]
The documentation is now correct.

**Comment by mashbur4** [comment]
Thank you so much for the help. I do have one other quick question. If I were to make both the x and y components to have a uniform distribution would the simulation be a complete flux or would the distributions increase at the same time essentially creating a diagonal line? Again thank you very much for your assistance.

**Comment by drobnyjt** [comment]
You're welcome! It will be the former, a uniform box; each instance of the uniform distribution is independent.
