### ISSUE TITLE
[bug] infinite loop in Python functions reflection_coefficient and sputtering_yield when angle == 90.0

### ISSUE THREAD

**Issue by drobnyjt** [lcpp-org/RustBCA#209]
**Description**
When angle is 90 degrees, surface refraction never kicks in and the particles travel parallel to the surface forever.

**To Reproduce**
Use sputtering_yield or reflection_coefficient with an angle >= 90 degrees.

**Expected behavior**
Either the code should panic, or it should nudge the angle downward to something like 89.9.

**Additional context**
Unclear which is better for the user - a panic or a nudge. Nudge at 90 seems reasonable, but if the code is given 91, what should happen? Should it panic, or needlessly run particles flying up out of the surface?

**Comment by dcurreli** [comment]
What happens physically? The energy landscape close to the surface is plenty of small perturbations, which will never leave a particle to fly parallel to the surface indefinitely. So I think nudging to some smaller angle would make sense.

**Comment by dcurreli** [comment]
All angles should be in the interval [0,90], by definition, right?

**Comment by drobnyjt** [comment]
Fixed on development branch; code now panics when incident angle <-90 or >90. Instead of using an if-statement to detect 90 or -90 degrees, the code simply nudges ux and uy in the opposite direction as before. This simultaneously avoids gimbal-lock at 0 and the issue at 90-degrees. There is the possibility of an incident angle input that is exactly opposite the nudge. That issue should be handled in the particle creation or in the collision sections of the code; the issue is very unlikely to come up, but the code should be robust to the possibility, especially if someone is (mis)using these functions in such a way that many, many random angles are being input.
