### ISSUE TITLE
[benchmark] Hydrogen Implantation in Titanium: Experiment and SRIM

### ISSUE THREAD

**Issue by drobnyjt** [lcpp-org/RustBCA#215]
**Description**
_Improvement of titanium hydrogenation by low energy ion irradiation_, published in the International Journal of Hydrogen Energy, includes a comparison of experimental data (ERDA) to SRIM. The two plots are significantly different from each other, from which the authors conclude the following:

"The experimental data indicates that hydrogen depth profile is slightly broader than the SRIM simulation, where the experimental value for the ion projected range is 81 nm. **This result suggests that a radiation induced diffusion of hydrogen into the titanium bulk is taking place during implantation**; which could be related to the high mobility of hydrogen atoms in titanium, increased by a thermal mechanism during implantation, even though low energy implantation is used during the experiment." (emphasis mine).

However, using their digitized data, a different conclusion can be reached when compared to RustBCA run with default values for hydrogen and titanium:

![h_ti_compare](https://github.com/lcpp-org/RustBCA/assets/37962344/f6a67aad-a886-45d7-b8ab-1add240d2001)
Figure 1: 5 keV H on Ti implantation distributions. SRIM results do not agree with the experimental data. RustBCA results agree very well.

It may in fact be that the SRIM stopping powers for low-energy proton implantation on titanium are incorrect - which would be surprising, given that the light ion stopping powers are supposed to be one place where SRIM is correct. Further investigation is warranted - particularly, ensuring that the authors' SRIM simulations were performed correctly by re-running them.

**Source**
https://doi.org/10.1016/j.ijhydene.2015.01.166

**Comment by dcurreli** [comment]
@drobnyjt  Nice comparison! Which potential are you using here for H/Ti? Is it attractive/repulsive or semi-classical?

**Comment by drobnyjt** [comment]
Added to wiki.
