### ISSUE TITLE
[question] Error in trimesh implementation despite watertight and fix_normals?

### ISSUE THREAD

**Issue by Sir-Goshawk** [lcpp-org/RustBCA#240]
I have 4 meshes, a [cube](https://github.com/lcpp-org/RustBCA/files/14632019/cube.txt), a [cylinder](https://github.com/lcpp-org/RustBCA/files/14632023/cylinder.txt), a 
[sphere.txt](https://github.com/lcpp-org/RustBCA/files/14632040/sphere.txt), and [another cube.txt](https://github.com/lcpp-org/RustBCA/files/14632035/correct_cube.txt)
ustBCA/files/14632031/sphere.txt).

I suspect the first cube and cylinder have issues, when inspecting the geometry with `trimesh.show()`, my window shows blank., as when running the particles it seems to think particles that are inside the objects aren't. 
I have tried `fix_normals` and `invert`, have checked `watertight`, `is_volume`, and `winding` is consistent.

In the sphere and second cube, I can see the objects with `trimesh.show()` and I don't see the same `inside` problem. Where most of the partners chosen in `choose_collision_partner` has a collision in `calculate_binary_collision` but for the previous two objects, most particles doesn't. When running line-by-line it seems that `inside` and `inside_energy_barrier` isn't working as intended, thinking particles are that inside the object aren't. 

So I'm not exactly sure what's the difference between the sphere and the second cube compared to the first cube and cylinder when all other parameters are equal.

**Comment by drobnyjt** [comment]
Hey @Sir-Goshawk. How are you making your meshes?

If you open the cube up in trimesh and look at its bounding box, it's much bigger than I think it should be:
```
print(mesh.bounding_box.extents) #prints array([2.e+10, 2.e+10, 1.e+01])
```
It looks like there are a handful of vertexes in strange places, such as this one:
```
[ 1.0000000000000e+010, 5.9128907143027e-030,-2.4576486329245e+00],
```
My guess would be that these are causing your issue.

**Comment by Sir-Goshawk** [comment]
Currently, I'm using gmsh to create the mesh, export it as a msh file format then using a python script and gmsh's api for python to extract and export the vertices and indices.
And apparently that might be the trailing 0s that distorts the values. I will have to check the meshes again.

**Comment by Sir-Goshawk** [comment]
After running a few repeated tests, yes I can say that was the issue. Thank you.
