### ISSUE TITLE
[bug] RustBCA simulations crashing above threshold energies

### ISSUE THREAD

**Issue by sonatav2** [lcpp-org/RustBCA#248]
**Description**
As shown in the sputtering_neon_tungsten.csv file, zero sputtering yields are printed above certain threshold energies where Yamamura still predicts non-zero sputtering yields. The batch job output files show that the simulations are crashing - they never print "Finished!". Tried multiple versions of RustBCA. Tried different ion and target material combinations, which changes the threshold energy above which the simulations crash. Tried increasing the number of nodes in the sbatch file. Tried exporting RUST_BACKTRACE=1 in the sbatch file. Tried changing the number of particles, which seems to have some effect (the issue occurs at lower threshold energies with more particles). Tried a different machine and OS.

**To Reproduce**
Using a November 2022 version (d87a41bb760f51aa70b06938bfda0ac253aef3fc) of RustBCA on the campus cluster because the rustbca_tables.py script isn’t compatible with newest version of RustBCA. TOML file included in the zip file is for the last RustBCA simulation run with the rustbca_tables.py script.

**Expected behavior**
Non-zero sputtering yields where there are zero sputtering yields in the csv file.

**Error messages, output files, or figures**
The csv file, rustbca_tables.py file, sbatch file, and the toml file from the last simulation are attached.

**System (please complete the following information):**
OS: Linux (Campus Cluster)
The issue also occurs on a Mac computer, although at different minimum energies.

**Additional context**
Likely to be a memory issue.

[neon_tungsten_crashed_sims.zip](https://github.com/user-attachments/files/15979330/neon_tungsten_crashed_sims.zip)

**Comment by drobnyjt** [comment]
Hi @sonatav2 - thanks for bringing this to my attention. I'll try to reproduce it on my end, but since you're looking at high energy heavy ion sputtering simulations, I agree with your assessment that this is an issue with RustBCA using too much memory.

Can you try increasing num_chunks (looks like it's on line 294 of the attached version of the python script) from 10 to 100, or even 1000? That will reduce the number of particles held in memory at one time and let the code print more often to the output files.

**Comment by dcurreli** [comment]
When I try to run the `.toml` here attached I get a mismatch on the data types for `triangles`. In the geometry block, `triangles` is expecting a list of `int` (three vertices from points that make up each triangle), but here the `.toml` file has a list of `float`. `Points` are also missing.

**Comment by drobnyjt** [comment]
@dcurreli Hi Davide - yep, it's using the older input file version before I switched to the getdp-style version. The quickest way to convert it to the most recent version of RustBCA is to use 0D mode instead by changing `densities` to `[n]` from `[[n, n]]`, adding `electronic_stopping_factor = 1.0`, and running with `cargo run --release 0D neon_tungsten_.toml`. It'll ignore the extra options in the input file.

**Comment by sonatav2** [comment]
Thanks @drobnyjt ! I increased num_chunks to 1000 and started running simulations at 2.0264e+4 eV, where they were crashing before. The simulations are completing and printing non-zero sputtering yields.
