### ISSUE TITLE
Avoid large TOML ascii input files at large particle count

### ISSUE THREAD

**Issue by dcurreli** [lcpp-org/RustBCA#26]

**Comment by drobnyjt** [comment]
HDF5 is implemented on the hdf5 and cpr_rootfinder branches; I have not decided if I want the code to exclusively use HDF5 for particle input, or to use a hybrid of HDF5 and the input.toml.

**Comment by drobnyjt** [comment]
This has been fixed on the cpr_rootfinder branch; hdf5 is listed as an optional dependency, and can be enabled using compilation flags. This avoids ever needing hdf5 installed when not in use.
