### ISSUE TITLE
[feature]

### ISSUE THREAD

**Issue by Stephen-Armstrong** [lcpp-org/RustBCA#73]
Remove or suppress warning about metadata from intel-mkl-src  in version requirement. 
![intel warning in Rust](https://user-images.githubusercontent.com/58577114/105556694-247c2200-5cd0-11eb-8e90-4aa6095a9cd7.JPG)

**Comment by drobnyjt** [comment]
Should be fixed on master; I've also fixed an unnecessary parentheses issue that was prompting a warning.
