### ISSUE TITLE
Best way to cite? [question]

### ISSUE THREAD

**Issue by jackstahl** [lcpp-org/RustBCA#78]
What's the best way to cite RustBCA?

**Comment by drobnyjt** [comment]
Good question - I'm working on a paper to submit to JOSS; depending on the context of what you're submitting you can either:

1. directly cite the repository as code
2. cite the RustBCA wiki as a website 
3. cite the JOSS paper (located in the `paper` directory of the repository) as either "unpublished manuscript" or "to be submitted to JOSS"

**Comment by jackstahl** [comment]
Thanks Jon. For the time being I'm citing the repository as code, but I'll keep an eye on the JOSS paper as well.
